### ISSUE TITLE
make brain load faster

### ISSUE THREAD

**Issue by jefferis** [jefferislab/NBLAST_on-the-fly#10]
Can we load the brain faster? e.g. by lowering precision as we have done elsewhere? Or just downsampling?

**Comment by ajdm** [comment]
Plotting of downsampled brain added in 668b3689134e753aec1309fb3f2ba7cc1ae11fee.

**Comment by jefferis** [comment]
Great. Did you actually see a speed improvement?! 

Gregory Jefferis

**Comment by ajdm** [comment]
Locally it's marginal, but on flybrain it goes from 7 units to 3 units.

**Comment by jefferis** [comment]
Great. That's sounds like a very useful improvement.
