### ISSUE TITLE
result report should link back to info about scoring

### ISSUE THREAD

**Issue by jefferis** [jefferislab/NBLAST_on-the-fly#39]
So people are reminded where to find out more about what the scores mean when they have them in front of them.

**Comment by ajdm** [comment]
Links added in 690db5e2456679ac5e7efa855c329229d4200d29.

**Comment by jefferis** [comment]
e.g. the info at http://flybrain.mrc-lmb.cam.ac.uk/si/nblast/www/how/ perhaps with a bit more tidy-up
