### ISSUE TITLE
progress bar errors

### ISSUE THREAD

**Issue by jefferis** [jefferislab/NBLAST_on-the-fly#40]
Trying to run locally with latest package versions and according to README.md instructions.

Getting error:

`ERROR: could not find function "progressInit"`

related to this I guess:

https://groups.google.com/forum/#!topic/shiny-discuss/JGmdRYCLRtE

Can we now ditch shinyincubator? @ajdm maybe you could try on a branch at least?

**Comment by ajdm** [comment]
I'll give it a go when I have power for my laptop tomorrow.

**Comment by ajdm** [comment]
Done in 2aacb05e2e1c80f780d72259b14acb211e52877c.

**Comment by jefferis** [comment]
Great stuff @ajdm! Let me do this [video demo](https://www.youtube.com/watch?v=cCDql94lSwI) first time without a hitch!
