### ISSUE TITLE
Consistently getting grey screen & no query results.  

### ISSUE THREAD

**Issue by dosumis** [jefferislab/NBLAST_on-the-fly#42]
From looking at Chrome dev tools - looks like this is the culprit: WebSocket connection to 'ws://flybrain.mrc-lmb.cam.ac.uk/si/nblast/on-the-fly/__sockjs__/824/91ripirg/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

Connecting from hotel in Japan.  Possibly quirk of local setup.

**Comment by ajdm** [comment]
I've been unable to reproduce this inside or outside of the Cambridge network, so I guess it's a quirk of the local setup.

**Comment by jefferis** [comment]
Thanks for the report @dosumis. Was also unable to reproduce off campus. Will close unless this recurred in another setting. Thanks, G.
