### ISSUE TITLE
Add comma separator to csv file

### ISSUE THREAD

**Issue by mmc46** [jefferislab/NBLAST_on-the-fly#44]
Currently the csv file to download the scores isn't comma separated, making it harder to isolate the fields.

**Comment by jefferis** [comment]
So there was another fix required here, that I only made after your last deployment. What's the present deploy strategy @ajdm?

**Comment by ajdm** [comment]
At the moment, it's ssh into flybrain and then ``git pull``.

**Comment by jefferis** [comment]
And then the next session started by a web user will use the updated code?

**Comment by ajdm** [comment]
Yes.
