### ISSUE TITLE
make one against all the default page

### ISSUE THREAD

**Issue by jefferis** [jefferislab/NBLAST_on-the-fly#45]
@mmc46 I think this is the most common use case, wouldn't you say. @ajdm should be quick!

**Comment by mmc46** [comment]
Yes, I think it is the most common.

**Comment by jefferis** [comment]
See http://www.inside-r.org/packages/cran/shiny/docs/updateTabsetPanel

**Comment by ajdm** [comment]
Done in f6e07840fa8d79b3c9337fcd650b6ab2d4b63e9a.
