### ISSUE TITLE
nblast on the fly about should start by linking back to main nblast site

### ISSUE THREAD

**Issue by jefferis** [jefferislab/NBLAST_on-the-fly#46]
... before talking about R packages etc. html is generated here

https://github.com/jefferislab/NBLAST_on-the-fly/blob/master/ui.R#L139

**Comment by jefferis** [comment]
i.e. http://jefferislab.org/si/nblast

**Comment by mmc46** [comment]
Commit d9c6acc79529174e6b23a8e751ce5f94f2778642

**Comment by jefferis** [comment]
Looks good to me. Just waiting on deployment when @ajdm has a moment.

**Comment by ajdm** [comment]
Deployed.
