### ISSUE TITLE
Automate deployment?

### ISSUE THREAD

**Issue by jefferis** [jefferislab/NBLAST_on-the-fly#49]
Just a placeholder, not high priority.

ideas: http://www.flaviobarros.net/2015/05/11/git-pushing-shiny-apps-with-docker-dokku/

**Comment by ajdm** [comment]
I thought we might be able to get away with a post-receive hook, but restarting the ``shiny-server`` process requires sudo.

**Comment by ajdm** [comment]
Slight error in previous version of Upstart script fixed below:
```
description "Shiny application server"

start on runlevel [2345]
stop on runlevel [016]

limit nofile 1000000 1000000

post-stop exec sleep 5

exec /opt/shiny-server/bin/shiny-server --pidfile=/var/run/shiny-server.pid >> /var/log/shiny-server.log 2>&1

respawn limit 3 25

respawn
```

**Comment by ajdm** [comment]
It looks like previous attempts at just pushing may have failed as there were some outstanding changes on flybrain. This last deployment ran the updated code without restarting ``shiny-server``.

**Comment by ajdm** [comment]
It seems to be a good idea to do a ``sudo restart shiny-server``, especially if the packrat library has changed.
