### ISSUE TITLE
Empty brain does not appear on non-first tabs

### ISSUE THREAD

**Issue by ajdm** [jefferislab/NBLAST_on-the-fly#55]
Spinner just sits there until the form is submitted. Quick tests locally suggest that this behaviour was actually introduced quite a few commits ago, before the spinner was implemented...

**Comment by ajdm** [comment]
It looks like this might be an issue with later versions of ``shiny``, or some other dependency, as I've now checked-out rather old versions for which I'm sure the behaviour previously was as expected and the problem remains.

**Comment by ajdm** [comment]
Even with other changes made since, as of 03707106842c23e1788910caba8832ea6283f4b1 this still does not work.

**Comment by jefferis** [comment]
Annoying but I think we can live with this if nothing else is broken. G.

**Comment by ajdm** [comment]
Closed as we have now removed tabs due to shiny/RGL issues.
