### ISSUE TITLE
switch vfb links to vfbdev stack browser

### ISSUE THREAD

**Issue by jefferis** [jefferislab/NBLAST_on-the-fly#56]

**Comment by jefferis** [comment]
http://vfbdev.inf.ed.ac.uk/site/stacks/index.htm?add=VFB_00010176

**Comment by jefferis** [comment]
OK What we actually want is whatever this points to:

bit.ly/vfbalpha

i.e. the url above should be:

http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?add=VFB_00010176

**Comment by jefferis** [comment]
@ajdm I guess you'll be deploying something soon enough ...

**Comment by ajdm** [comment]
> @ajdm I guess you'll be deploying something soon enough ...

Indeed. Deployed, along with one-tab layout changes.
