### ISSUE TITLE
add mirror check box

### ISSUE THREAD

**Issue by jefferis** [jefferislab/NBLAST_on-the-fly#57]

**Comment by ajdm** [comment]
Would this just be for the tracing, or for everything?

**Comment by jefferis** [comment]
Just the tracing. Would be great to have, but if it might get in the way of other stuff, let it be for now. Best, G.

**Comment by ajdm** [comment]
Added in 21daf853d6d1fa86a3c6144a258ee1c8654d2d3e. Doesn't seem to clash with anything.

**Comment by jefferis** [comment]
Super! G.
