### ISSUE TITLE
some vfb_annotations are skipped

### ISSUE THREAD

**Issue by jefferis** [jefferislab/NBLAST_on-the-fly#60]
there is an embedded single quote causing trouble

we should be doing:
```r
vfb_annotations <- read.table("annotation_map.tsv", header=TRUE, sep="\t", quote = "")
```

**Comment by jefferis** [comment]
Fixed here:
https://github.com/jefferislab/NBLAST_on-the-fly/commit/5a7396024271f497959720e5631904dbc3876276 but not too sure which branch is live at this point

**Comment by ajdm** [comment]
Included in master now.
