### ISSUE TITLE
remove autocomplete for pairwise search

### ISSUE THREAD

**Issue by jefferis** [jefferislab/NBLAST_on-the-fly#62]
I think it's quite a lot of overhead for relatively little utility. The page is 1Mb with the typeahead and 30kb without. Pairwise comparison will be the least used search type I think.

**Comment by jefferis** [comment]
views @ajdm  @mmc46

**Comment by mmc46** [comment]
I think it would be fine to remove the autocomplete. We'll see if someone complains.

**Comment by ajdm** [comment]
Removed in 48875cbef716c04fbc6d5644185b1d66fc4d4d4d.
