### ISSUE TITLE
Add query neuron name to results section

### ISSUE THREAD

**Issue by mmc46** [jefferislab/NBLAST_on-the-fly#64]
Currently the query neuron is only shown in the input box. I think it would be better if it was also shown in the results section.

Either by changing the 'NBLAST results' title to 'NBLAST results for neuron X' or by adding a line underneath it with 'Query: neuron X'.

**Comment by jefferis** [comment]
Yes, good suggestion!

**Comment by ajdm** [comment]
Added in 5f4d3aedb93973dec23fdd5194f55262ea1b25cb.
