### ISSUE TITLE
should we plot cell bodies?

### ISSUE THREAD

**Issue by jefferis** [jefferislab/NBLAST_on-the-fly#69]
I think we may as well plot cell bodies. It wouldn't result in slower results download although it could make the webgl visualisation a bit less responsive when there are a lot of somata.

Views @ajdm @mmc46?

**Comment by mmc46** [comment]
I'd prefer to see cell bodies, if it doesn't impact on the rest.

**Comment by jefferis** [comment]
I've just tried it and I think it looks quite a bit better. I'm now deploying. Best, G.

**Comment by jefferis** [comment]
closed by bfaa9099b1b7bfd70140d699aa1ec0ee024536d3
