### ISSUE TITLE
Error: "cannot allocate vector of size 187.0 Mb"

### ISSUE THREAD

**Issue by josesho** [jefferislab/NBLAST_on-the-fly#70]
When uploading a skeletonised neuron (.NRRD format) for an all-by-all NBLAST, I encounter the error "cannot allocate vector of size 187.0 Mb".

**Comment by jefferis** [comment]
Hi @josesho, Do you want to give this a go and see if it behaves better for you now. Thanks, Greg.

**Comment by josesho** [comment]
I still get the same error -- maybe there is an issue with my own file?

**Comment by josesho** [comment]
Downsampling before skeletonisation seems to reduce memory usage, allowing NBLAST to run normally.

I notice, however, the origin has changed, as noted in [Pull #65 ](https://github.com/jefferislab/NBLAST_on-the-fly/pull/65). I've updated that thread over there. 

I'd consider this issue properly closed! Thanks.

**Comment by ajdm** [comment]
As a further backup for the version we're running on our server, I've just added 1 GB of swap space.

**Comment by jefferis** [comment]
Thanks @ajdm !
