### ISSUE TITLE
Add button to display top10 in VFB

### ISSUE THREAD

**Issue by mmc46** [jefferislab/NBLAST_on-the-fly#73]
Currently, we can click to display each neuron from NBLAST results one by one on the VFB viewer. After displaying the first, the second opens a new viewer tab, but it's added to the same session, so that's fine.

It would be good, though, if there's was an option to display the top10 all in one go, instead of having to do it one by one. I guess this should be possible using the viewer urls

http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?add=VFBt_00100000,VFBi_00011778,VFBi_00006432

**Comment by ajdm** [comment]
> http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?add=VFBt_00100000,VFBi_00011778,VFBi_00006432

I can't get this page to load correctly. I just end up with a menu, some buttons, a grey box (where I guess the viewer should be) and some loading spinners.

**Comment by mmc46** [comment]
There are some issues with loading of pages, which I’ve just come across as well. I’ll let you know when it’s fixed.

**Comment by mmc46** [comment]
The pages are loading ok now.

**Comment by ajdm** [comment]
I can get the Janelia adult brain stack to load, but nothing else. Copying and pasting the

> ?add=VFBt_00100000,VFBi_00011778,VFBi_00006432

to the end of the page URL seems to do nothing.

**Comment by mmc46** [comment]
I just tested these and it worked fine

http://vfbdev.inf.ed.ac.uk/site/stacks/index.htm?add=VFBt_00100000,VFBd_00100031,VFBi_00021737,VFBi_00023456,VFBi_00020842

http://vfbsandbox3.inf.ed.ac.uk/site/stacks/index.htm?add=VFBt_00100000,VFBd_00100035,VFBd_00100031,VFBi_00020381,VFBi_00020756,VFBi_00020842,VFBi_00023694

**Comment by ajdm** [comment]
These links all work for me if I use ``vfbdev``, and all fail if I use ``vfbsandbox3``. Am I okay to use ``vfbdev`` throughout?

**Comment by mmc46** [comment]
It should be with vfbsandbox3, the stable one. 
I'll let Rob know, vfbsandbox3 is now failing for me too.

**Comment by jefferis** [comment]
Hi @mmc46,

I can only get the vfbdev url to behave (Chrome, Safari). 

@robbie1977 I guess there is a fix that will be applied to vfbsandbox3 sometime soon.

Thanks, Greg.

**Comment by Robbie1977** [comment]
Just fixed an annoying glitch in the data store - 2 seconds should be back

**Comment by jefferis** [comment]
thx @Robbie1977

**Comment by Robbie1977** [comment]
Let me know if any issue persist? (check the cache is cleared)

**Comment by ajdm** [comment]
Added in 80f486856a5ff45fec8f71ccde8be1d2a27d0365. The stack viewer seems to work very well now, thanks @Robbie1977.
