### ISSUE TITLE
Menu layout issue on mobile

### ISSUE THREAD

**Issue by Robbie1977** [jefferislab/NBLAST_on-the-fly#75]
The nav bar obscures the page on small screens
![image](https://cloud.githubusercontent.com/assets/4630768/9930342/f7d7b7f0-5d2a-11e5-968b-71b187ee6f62.png)

**Comment by jefferis** [comment]
Thanks, Rob. @ajdm I think this is in the "nice to fix" category since we're not really targeting mobile given the fairly heavy use of webgl.

**Comment by ajdm** [comment]
This appears to be an iOS Safari issue, as it's fine on Android and Safari on small desktop screens. Unfortunately I don't have an iPhone or iPad to hand to debug this with, so I'm afraid I'll have to leave it for now.

**Comment by Robbie1977** [comment]
Again I agree this is low priority but just wanted to advise (as have spent way too long fixing these issues on VFB) it's not actually the browser type it's how bootstrap handles the collapsed state which occurs at 767px width and below so can simply test in any desktop browser.

The current menu defaults to stacked items which should work fine if you increase the offset of the main page.

if you include in the CSS this should resolve:

@media screen and (max-width: 767px) {
    body {
        padding-top: 180px;
    }
}

**Comment by ajdm** [comment]
This looks to be fixed after the rewrite.
