### ISSUE TITLE
Update to use rglwidget

### ISSUE THREAD

**Issue by ajdm** [jefferislab/NBLAST_on-the-fly#77]
There's a new package by Duncan Murdoch that's designed to allow ``rgl`` outputs in ``shiny`` apps. We should switch over to using that, rather than the outdated ``shinyRGL`` package and my assorted hacks. This should hopefully stop the thing from breaking every time I try and update something...

**Comment by jefferis** [comment]
Thanks for the heads up. That sounds very interesting!

Also I have done some new work in two packages flynblastscores and vfbr that enable remote score queries using a server being run by Rob Court of VFB. This might help to factor some of the logic out or even offload all the handling of large data onto another machine (I haven't done anything with queries that actually require new computations) to make us more flexible.

Finally I have a feeling we are still using rgl non headless for the shiny server and I guess we should be using rglUseNULL=T there (which may probably happen with changes we have discussed for nat).

**Comment by ajdm** [comment]
There's already
```r
if(!interactive()) {
  message("rgl use NULL device to avoid problems on headless servers")
  options(rgl.useNULL=TRUE)
} else {
  message("interactive mode - full rgl")
}
```
in the top of the ``server.R`` file, which I think you put in there a while ago. Annoyingly, while I was testing out the new version of nat, something broke and when it was reset using packrat is started complaining about my ``inRows`` overwrite (used to reduce the accuracy to which vertex locations are specified, to decrease load time). I've now removed those lines and it's complaining that it can't find a method of starting a webGL scene, so I guess I've messed up packrat somehow, as it still says it's using nat version 1.7.2. I'll fix and then try and see if this will be easy to implement.

**Comment by jefferis** [comment]
OK. Thanks for clarification re headless. So that will not be a change.

Not sure about the apparent packrat issue.

**Comment by ajdm** [comment]
The packrat issues seem to have been caused by some packages being 
silently updated when trying to upgrade to the latest version of nat 
(rgl in particular). It's fixed again and I'll try some changes on a 
separate checkout.

**Comment by jefferis** [comment]
Note that as of time of writing rglwidget on CRAN still has a showstopper bug with surfaces with alpha transparency. This has been fixed on rforge. See https://github.com/rforge/rgl/commit/e51a011bffff91338d85b55513ab03596d8e7479

**Comment by ajdm** [comment]
We're now running on an rforge version, so I think we can consider this closed.
