### ISSUE TITLE
Adding a help menu

### ISSUE THREAD

**Issue by mmc46** [jefferislab/NBLAST_on-the-fly#80]
There is currently no clear way for people to get help. The googlegroups is only mentioned in the main NBLAST site. 

Possibilites:
1) Add a 'Help' tab on to the toolbar, to the right of 'About', which would link directly to the googlegroups
2) Add a 'Contact' section to 'About' page similar to the one in the main site

**Comment by ajdm** [comment]
Some help from the main site added in 8a3d4800a93b7c28bb42e78c3d8146b265e23f1c. Is there anything else we should explicitly say?

**Comment by mmc46** [comment]
Nothing I can think of.
