### ISSUE TITLE
Add more text to skeleton tab

### ISSUE THREAD

**Issue by mmc46** [jefferislab/NBLAST_on-the-fly#81]
Add some more text to the web app that makes it clear that the skeleton does need to be registered to one of the template brains we support

**Comment by ajdm** [comment]
I've added a bold notice in 0c9a7ffd59c0710538646f4ba6a7a69462e31e31. Do you think this is suitable, or should we be more verbose?

**Comment by mmc46** [comment]
I think it is ok. But I'd move it up, to above "Query".
And change ", below" to ", see below".

**Comment by ajdm** [comment]
Done in 097e7d4cf5e64cf97bd6a5cc53a8b3c9a4bec317.
