### ISSUE TITLE
Add example of FlyCircuit ids that can be used

### ISSUE THREAD

**Issue by mmc46** [jefferislab/NBLAST_on-the-fly#84]
I've noticed that nowhere do we show an example of a FlyCircuit id that can be used.
This would be quite useful for a naive user.

Can an example be added to One vs all, Pairwise and GAL4 tabs? Either as a placeholder in the search box or simple an extra sentence at the end of Instructions.

**Comment by ajdm** [comment]
Defaults added in c893f80beed933f1e94588557039dec9f140e535. I think they're okay, but it might be worth changing the GAL4 one as, while the top hit is pretty much perfect, the other hits are perhaps not as good as they would be with other initial inputs.
