### ISSUE TITLE
Update VFB link to main site

### ISSUE THREAD

**Issue by mmc46** [jefferislab/NBLAST_on-the-fly#85]
The link from the GAL4 tab "View all these hits on Virtual Fly Brain." points to vfbdev.

http://vfbdev.inf.ed.ac.uk/site/stacks/index.htm?add=VFB_00021268,VFB_00020478,VFB_00020518,VFB_00021521,VFB_00022031,VFB_00022894,VFB_00022834,VFB_00020932,VFB_00022353,VFB_00022681&clear=true

There are also links in one agains all tab to VFB sandbox3, that can point to main site.

It can now point to the main site (virtualflybrain.org), since the beta site is now live.

**Comment by ajdm** [comment]
I've updated all the links to point to the main VFB site as of d0cc78badca930a4f88e25494668db98e727fc4f, but there's one remaining due to a package option in ``vfbr``.
