### ISSUE TITLE
Remove spaces from inputted FlyCircuit ids

### ISSUE THREAD

**Issue by ajdm** [jefferislab/NBLAST_on-the-fly#86]
There's a chance spaces could be erroneously copied across from various sources, which would make the app fail 'invisibly'. The easiest fix is to just remove all spaces from text input fields when processing their values.

**Comment by jefferis** [comment]
I would remove all non alphanumeric. G.

**Comment by ajdm** [comment]
Removed all non-alphanumeric, non-hyphens in 822d694e6e50b8d3bc033fcc8f079f89e164e11c.
