### ISSUE TITLE
Add query neuron to results

### ISSUE THREAD

**Issue by mmc46** [jefferislab/NBLAST_on-the-fly#90]
Can the query neuron be added to 'One against all', and GAL4 tabs?
Similar to the pairwise tab.

"NBLAST results
Query neuron: fru-M-200266"

**Comment by ajdm** [comment]
One against all query neuron added in b6ac8eb9c9ca828df23ffc6bcdf4166f448feb36. GAL4 query neuron added in 0704d8b0505968a5380288a43209cbee0d8ff961.
