### ISSUE TITLE
Opening images in VFB -> vfbdev.  This should be switched to public VFB

### ISSUE THREAD

**Issue by dosumis** [jefferislab/NBLAST_on-the-fly#91]
Prior to the public launch of VFB 1.5, this behaviour made sense, but not any more.  Can you switch ASAP if this is easy to do?  (I'm currently demo-ing VFB + NBlast at the GSA meeting.  Lots of interest in Blasting neurons to GAL4 lines.)

**Comment by ajdm** [comment]
Added in f685dbc63193dfb60a39d7b73a15ecd62d498100 and now running on flybrain. Please let me know if I've missed any of the links. Thanks.

**Comment by dosumis** [comment]
Wow, that was fast.  Thanks!
