### ISSUE TITLE
Add mention of Neuron paper

### ISSUE THREAD

**Issue by mmc46** [jefferislab/NBLAST_on-the-fly#92]

**Comment by mmc46** [comment]
Added in 7d66cf84c931c4f8b636055ef06d809e192a03a9

**Comment by jefferis** [comment]
Cleaning up issues. Is this done @mmc46?

**Comment by mmc46** [comment]
Yes, but not pushed live.

**Comment by jefferis** [comment]
Maybe Ashley did this coincidental in one of his recent changes?

**Comment by jefferis** [comment]
It's live now under About/Help so closing.
