### ISSUE TITLE
Server very slow

### ISSUE THREAD

**Issue by mmc46** [jefferislab/NBLAST_on-the-fly#93]
The searches (and website loading) are really slow. 
A GAL4 search took 2min30.

I'm on Firefox 49.0

**Comment by ajdm** [comment]
Is this from home, outside the CUDN? My internet connection at the moment
is terrible, so I can't check, but I'll give it a go on the CUDN once I get
home later tonight.

**Comment by mmc46** [comment]
PDN network, ethernet

**Comment by ajdm** [comment]
Hmm, it's slow on my connection as well. ``top`` doesn't show anything 
particularly odd on flybrain, except that we only have 200 MB of memory 
left. It might be that a quick reboot of the VM sorts the problem. 
@jefferis, what do you think to rebooting the VM?

**Comment by jefferis** [comment]
> @jefferis, what do you think to rebooting the VM?

no objections. Wonder what's filling it up.

**Comment by ajdm** [comment]
Rebooting it seems to have worked. It looks like MySQL might be filling 
it up (I vaguely recall noticing this before).

**Comment by jefferis** [comment]
I'm closing this as performance generally seems OK of late (and should be more reliable when we move to a VFB hosted server).
