### ISSUE TITLE
Upload a tracing - T1 template problems

### ISSUE THREAD

**Issue by obarnstedt** [jefferislab/NBLAST_on-the-fly#96]
Hi,

I keep running into problems on my system trying to upload a tracing using the T1 - Vienna template.
While the JFRC2 works absolutely fine in general, whenever I select T1 for my tracings, I receive this error message on the top left corner of the 3D rendering space:

> Error: Invalid vertex names

To be more precise, this message appears if I first upload a tracing, and then select T1. If I first select T1, it loads the 3D rendering, and if I then upload a tracing and press the button, nothing happens.
This problem has been recurring with different SWC files (that work fine for JFRC2, but of course misaligned). I'm using macOS sierra 10.12.1 (16B2555) with Safari 10.0.1, but the same problem occurs with Chrome v54.

Thanks for all the great work on NBLAST; it has helped me a lot so far, and mostly works great!
Oliver

**Comment by jefferis** [comment]
Thanks, Oliver. It looks like some bridging registrations were missing on that machine.

**Comment by obarnstedt** [comment]
Hi Greg,
error is gone, works perfectly fine now.
Thanks a lot for the very quick fix!
Oliver
